### ISSUE TITLE
No Upi app found crash!

### ISSUE THREAD

**Issue by AnkitVerma8584** [PatilShreyas/EasyUpiPayment-Android#115]
I tested my app which had not upi app installed. While trying to start payment. App crashes with FATAL Exception saying  No UPI app exists on this device to perform this transaction

Here is my Logcat

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.libhub/dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity}: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app exists on this device to perform this transaction.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
     Caused by: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app exists on this device to perform this transaction.
        at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.throwOnAppNotFound$EasyUpiPayment_release(PaymentUiActivity.kt:128)
        at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.onCreate(PaymentUiActivity.kt:62)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8506) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
#112  @PatilShreyas

**Comment by AnkitVerma8584** [comment]
I have already enclosed the code in try catch but there is a crash anyways.
This crash didn't happen in version 2.2 .There it showed a toast that no upi app found. But here it crashes

**Comment by aniket5687** [comment]
> I tested my app which had not upi app installed. While trying to start payment. App crashes with FATAL Exception saying No UPI app exists on this device to perform this transaction
> 
> Here is my Logcat
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.libhub/dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity}: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app exists on this device to perform this transaction.
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
> at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
> at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:246)
> at android.app.ActivityThread.main(ActivityThread.java:8506)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
> Caused by: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app exists on this device to perform this transaction.
> at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.throwOnAppNotFound$EasyUpiPayment_release(PaymentUiActivity.kt:128)
> at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.onCreate(PaymentUiActivity.kt:62)
> at android.app.Activity.performCreate(Activity.java:8198)
> at android.app.Activity.performCreate(Activity.java:8182)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968) 
> at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
> at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
> at android.os.Handler.dispatchMessage(Handler.java:106) 
> at android.os.Looper.loop(Looper.java:246) 
> at android.app.ActivityThread.main(ActivityThread.java:8506) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
> #112  @PatilShreyas

I have the same problem. my mobile is supported android 11. I have update the latest version for android 11 support. But not working same issue No UPI app. Please Solve This Problem

**Comment by aniket5687** [comment]
I have the same problem. my mobile is supported android 11. I have update the latest version for android 11 support. But not working same issue No UPI app. Please Solve This Problem

**Comment by PatilShreyas** [comment]
Thanks for reporting this issue. Looks like this is happening for devices having Android 11. Currently, I don't have any device having Android 11 to test this change. I've tried to fix this change and attached APK here 👇🏻.

[***Download Sample APK***](https://github.com/PatilShreyas/EasyUpiPayment-Android/raw/v3.0.3-dev/app/app-debug.apk)

It's my humble request to test the attached APK and please let me know if it works as expected. If it works, I'll be happy to release the new version `v3.0.3`.

**Comment by aniket5687** [comment]
Not working Phone pe app and Google pay App install on my Phone but Error
was showing

**Comment by PatilShreyas** [comment]
Thanks, this has been fixed in the latest release `v3.0.3`.

**Comment by aniket5687** [comment]
sample code upload in GitHub account. Please

**Comment by KhadkaRabindra** [comment]
> Thanks, this has been fixed in the latest release `v3.0.3`.

I am still getting this issue on v3.0.3 . Please help.

**Comment by SuvarnaPBhadane** [comment]
This issue exist in your sample apk as well. Please look into this @PatilShreyas . So many people are facing this issue who are using your library. Please fix this on priority

**Comment by yesarpit** [comment]
@PatilShreyas  Any thoughts on this one?
