### ISSUE TITLE
[BUG] App Crashed while GPay Payment 

### ISSUE THREAD

**Issue by basheerbsr79** [PatilShreyas/EasyUpiPayment-Android#129]
Write information about Bug/Feature Request here
Can't do GPay Payment on Moto G4 Plus Device Getting App Crash and Log will be the App not Found Exception. i will attaching video and my phone spec .

Android Studio Console 

2021-07-10 18:29:17.344 31469-31469/com.example.easyupipayment E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.easyupipayment, PID: 31469
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.easyupipayment/dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity}: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app with package name 'com.google.android.apps.nbu.paisa.user' exists on this device to perform this transaction.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app with package name 'com.google.android.apps.nbu.paisa.user' exists on this device to perform this transaction.
        at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.throwOnAppNotFound$EasyUpiPayment_release(PaymentUiActivity.kt:128)
        at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.onCreate(PaymentUiActivity.kt:62)
        at android.app.Activity.performCreate(Activity.java:6672)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 

![Screenshot_20210710-181047](https://user-images.githubusercontent.com/74948893/125163443-d342ea80-e1aa-11eb-91a6-2dc79da8fd83.png)

https://user-images.githubusercontent.com/74948893/125163620-9b887280-e1ab-11eb-8170-aded8355aefb.mp4

**Comment by katesaikishore** [comment]
+1
