### ISSUE TITLE
App Crash (No UPI app found on device.)

### ISSUE THREAD

**Issue by arjunpatel1** [PatilShreyas/EasyUpiPayment-Android#157]
FATAL EXCEPTION: main
    Process: com.payment.ammu, PID: 21361
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.payment.ammu/dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity}: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app exists on this device to perform this transaction.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app exists on this device to perform this transaction.
        at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.throwOnAppNotFound$EasyUpiPayment_release(PaymentUiActivity.kt:128)
        at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.onCreate(PaymentUiActivity.kt:62)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)

**Comment by HeroKince** [comment]
What is the Android system version？

**Comment by AbhinavChauhan97** [comment]
happened with me also on android 11 in v3.0.3

**Comment by harshadkanziya-in** [comment]
Please help as still issues on 3.0.3 version
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.upidemo, PID: 8623
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.upidemo/dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity}: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app with package name 'net.one97.paytm' exists on this device to perform this transaction.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2048)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7438)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:989)
     Caused by: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app with package name 'net.one97.paytm' exists on this device to perform this transaction.
        at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.throwOnAppNotFound$EasyUpiPayment_release(PaymentUiActivity.kt:128)
        at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.onCreate(PaymentUiActivity.kt:62)
        at android.app.Activity.performCreate(Activity.java:7803)
        at android.app.Activity.performCreate(Activity.java:7792)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3288)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2048)

**Comment by SuvarnaPBhadane** [comment]
happened with me also on android 12 in v3.0.3. Only Gpay is working. PayTm, PhonePay other apps not working.

2022-09-02 15:32:17.809 22260-22260/com.idragonpro.andmagnus E/PaymentUiActivity: No UPI app found on device.

2022-09-02 15:32:17.826 22260-22260/com.idragonpro.andmagnus E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.idragonpro.andmagnus, PID: 22260
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.idragonpro.andmagnus/dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity}: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app with package name 'com.phonepe.app' exists on this device to perform this transaction.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3810)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3972)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2374)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8223)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
     Caused by: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app with package name 'com.phonepe.app' exists on this device to perform this transaction.
        at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.throwOnAppNotFound$EasyUpiPayment_release(PaymentUiActivity.kt:128)
        at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.onCreate(PaymentUiActivity.kt:62)
        at android.app.Activity.performCreate(Activity.java:8130)
        at android.app.Activity.performCreate(Activity.java:8110)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3779)

**Comment by arjunpatel1** [comment]
we are facing this issue in all version.
if enter wrong upi pin then after back getting success response.

**Comment by Rohitbagul003** [comment]
Facing this crash on :No UPI app found on device.
is there any way i can fix this?

**Comment by yesarpit** [comment]
Any solution yet? I am trying to call these methods after bridging from react native.

**Comment by fontend-noah** [comment]
> Any solution yet? I am trying to call these methods after bridging from react native.

Hi, Have you succeeded? I am also trying to integrate into the RN project. I plan to package it as aar and introduce it, but I have encountered trouble and the build failed....
I was a web developer before. I have never been exposed to mobile devices before and I don’t understand Android.....
If you succeed, can you show me your example?
