### ISSUE TITLE
Error has still not resolved in the new version related to issue #21

### ISSUE THREAD

**Issue by suryabhairaj** [PatilShreyas/EasyUpiPayment-Android#26]
![image](https://user-images.githubusercontent.com/31375031/74777384-5f572800-52bf-11ea-98e9-f91a9a6f3890.png)

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4400, result=-1, data=Intent { (has extras) }} to activity {com.example.raj.checker/com.shreyaspatil.EasyUpiPayment.ui.PaymentUiActivity}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4423)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4465)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at com.shreyaspatil.EasyUpiPayment.ui.PaymentUiActivity.getQueryString(PaymentUiActivity.java:143)
        at com.shreyaspatil.EasyUpiPayment.ui.PaymentUiActivity.getTransactionDetails(PaymentUiActivity.java:151)
        at com.shreyaspatil.EasyUpiPayment.ui.PaymentUiActivity.onActivityResult(PaymentUiActivity.java:111)
        at android.app.Activity.dispatchActivityResult(Activity.java:7590)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4416)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4465) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

same thing happened while using BHIM UPI..

**Comment by ImPDP** [comment]
@suryabhairaj Did you solved this problem? I'm facing this issue. The payment is completing successfully but it doesn't callback to the activity.

**Comment by PatilShreyas** [comment]
Can you please describe how to produce this error?

**Comment by ImPDP** [comment]
@PatilShreyas Some of the customers facing the issue, the certainty of the issue is uncommon. It happens hardly but it is happening. just handle the exception in the line where the error is happening in PaymentUIActivity

**Comment by PatilShreyas** [comment]
Okay. Thanks. I'll fix it soon

**Comment by PatilShreyas** [comment]
This is fixed and implemented in version `v2.1`. Thanks!

**Comment by ImPDP** [comment]
Will implement in few days. I'm just asking. Is that exception is handled and sent as a success callback? Since this is happening only in successfull transactions.

**Comment by PatilShreyas** [comment]
This issue is solved and implemented in v2.1. Thanks for thinking about
contributing.
